// Colors
export const COLORS = {
  textPrimary: '#333',
  textSecondary: '#555',
  price: '#27ae60',
  removeButton: '#d9534f',
  decrement: '#ff6b6b',
  increment: '#4CAF50',
  shadow: '#000',
  overlayBackground: 'rgba(0,0,0,0.5)',
  white: '#fff',
  inactiveDot: 'gray',
  animationDot: 'gray',
  cartIcon: 'black',
  badgeBackground: 'red',
  badgeText: 'white',
  containerBackground: '#f5f5f5',
  buttonBackground: '#ff6347',
  emptyCartText: '#555',
  shopButtonBackground: '#1e90ff',
  shadowColor: '#000',
  cardBackground: '#fff',
  priceColor: '#27ae60',
  iconColor: 'gray',
  messagePrimary: '#333',
  messageSecondary: '#777',
};

// Strings
export const STRINGS = {
  quantityLabel: 'Quantity:',
  productDetails: 'ProductDetails',
  qtyLabel: 'Qty:',
  orderSummary: 'Order Summary',
  emptyCartMessage: 'Your cart is empty.',
  goShopping: 'Go Shopping',
  subtotal: 'Subtotal:',
  tax: 'Tax (10%):',
  shipping: 'Shipping:',
  total: 'Total:',
  placeOrder: 'Place Order',
  shop: 'Shop',
  checkout: 'Checkout',
  confirmationMessage: 'Order placed successfully!',
  returnToHome: 'Return to Home',
  cartEmpty: 'Your cart is empty',
  addItems: 'Add items to your cart to start shopping!',
  addToCart: 'Add to Cart',
  specifications: 'Specifications',
  reviews: 'Reviews',
  buttons: 'Buttons',
  dpi: 'DPI',
  lighting: 'Lighting',
  weight: 'Weight',
  rating: 'Rating',
  noProducts: 'No products available for this tag.',
  noTags: 'No tags available.',
  searchPlaceholder: 'Search products',
  noResults: 'No products match your search.',
};
